Repository validmind/validmind-library, pull requests merged in 2024-12, with the labels that each got.

#243 [SC 7521] Move capital markets notebooks from code sharing to code samples
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
  notebooks/code_sharing/capital_markets/OptionPricer.ipynb
  notebooks/code_sharing/capital_markets/option_pricing_models_vm.ipynb
  validmind/tests/comparison.py
  validmind/utils.py
Labels: documentation, internal, highlight

#257 Improved README.pypi.md
  README.pypi.md
  pyproject.toml
  validmind/__version__.py
Labels: internal

#252 chore: removing metrics references
  validmind/vm_models/result/result.py
Labels: internal, chore

#259 Some more outdated client library references
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/r/r_customer_churn_demo.Rmd
  notebooks/code_sharing/r/r_customer_churn_demo_xgboost.Rmd
  notebooks/code_sharing/r/r_mortality_demo.Rmd
  notebooks/code_sharing/r/r_time_series_data_validation.Rmd
  notebooks/code_sharing/r/r_time_series_model_validation.Rmd
  pyproject.toml
  r/validmind/DESCRIPTION
  validmind/__init__.py
  validmind/__version__.py
Labels: internal

#260 Prod 2.5.25 to main
  README.md
  README.pypi.md
  poetry.lock
  pyproject.toml
Labels: internal

#265 Hotfix/fix listing of tasks and tags
  pyproject.toml
  validmind/__version__.py
  validmind/tests/load.py
Labels: bug, internal

#267 Bump Version to 2.6.9
  pyproject.toml
  validmind/__version__.py
Labels: internal, chore

#268 Fix Intro for Model Developers Notebook
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal, chore

#270 Hotfix for Required Inputs Formatting
  pyproject.toml
  validmind/__version__.py
  validmind/tests/load.py
Labels: bug, internal

#263 Add Initial Support for Post-Processing Functions
  .github/workflows/prod_patches_to_main.yaml
  notebooks/code_sharing/post_processing_functions.ipynb
  pyproject.toml
  validmind/__init__.py
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/ROCCurve.py
  validmind/tests/output.py
  validmind/tests/run.py
  validmind/utils.py
  validmind/vm_models/figure.py
  validmind/vm_models/result/__init__.py
  validmind/vm_models/result/result.py
Labels: enhancement, highlight

#264 [SC 7728] Include data quality tests in option pricer model notebooks
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
Labels: enhancement, internal

#272 [SC 7726] Create graphs in the capital markets model
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#276 feat: test [all] install target in integration tests
  .github/workflows/integration.yaml
Labels: internal, chore

#274 [SC-7759] Exposing static descriptions in test results
  pyproject.toml
  tests/test_unit_tests.py
  tests/unit_tests/model_validation/sklearn/test_ROCCurve.py
  validmind/__version__.py
  validmind/tests/run.py
  validmind/vm_models/result/result.py
Labels: internal

#277 fix: join unit metrics docstrings for composite tests doc
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: bug, internal

#273 [SC 7727] Greeks tests for option pricer model
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
Labels: internal

#278 [SC 7819] Include Implied volatility surface test
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
Labels: internal

#275 Add Better Handling for Generated Descriptions
  validmind/ai/test_descriptions.py
  validmind/vm_models/result/result.py
Labels: internal, chore
