Repository validmind/validmind-library, pull requests merged in 2024-08, with the labels that each got.

#152 [SC 5587] Initial support ongoing monitoring through header
  tests/test_api_client.py
  validmind/api_client.py
Labels: documentation, internal

#151 Fix: Don't Include Internal Columns in Test Results
  .vscode/settings.json
  pyproject.toml
  tests/test_client.py
  tests/test_dataset.py
  tests/test_run_all_tests.py
  validmind/__version__.py
  validmind/client.py
  validmind/vm_models/dataset/dataset.py
  validmind/vm_models/dataset/utils.py
Labels: bug, internal

#156 [SC-5709] Fix figure titles mismatch when using input grid
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: bug, internal

#155 Feat: Mechanism for Filtering Columns in a Dataset when Running a Test
  notebooks/how_to/filter_input_columns.ipynb
  validmind/client.py
  validmind/input_registry.py
  validmind/tests/data_validation/DatasetDescription.py
  validmind/unit_metrics/__init__.py
  validmind/vm_models/__init__.py
  validmind/vm_models/dataset/dataset.py
  validmind/vm_models/input.py
  validmind/vm_models/model.py
  validmind/vm_models/test_context.py
Labels: enhancement

#159 Pass X-MONITORING on every request
  .github/workflows/ai_explain.py
  .github/workflows/ai_explain.yaml
  pyproject.toml
  validmind/__version__.py
  validmind/api_client.py
Labels: internal

#158 [SC-5732] Fix inconsistent AUC calculations using class predictions instead of prediction probabilities
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/ClassifierPerformance.py
  validmind/tests/model_validation/sklearn/ClusterPerformance.py
  validmind/tests/model_validation/sklearn/MinimumROCAUCScore.py
  validmind/unit_metrics/classification/sklearn/ROC_AUC.py
Labels: bug, internal

#154 [SC 5588] Create demo notebook for ongoing monitoring
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/ongoing_monitoring/xgboost_model.model
  pyproject.toml
  scripts/add_test_description.py
  validmind/__version__.py
  validmind/tests/__types__.py
  validmind/tests/model_validation/sklearn/MinimumROCAUCScore.py
  validmind/tests/ongoing_monitoring/FeatureDrift.py
  validmind/tests/ongoing_monitoring/PredictionAcrossEachFeature.py
  validmind/tests/ongoing_monitoring/PredictionCorrelation.py
  validmind/tests/ongoing_monitoring/TargetPredictionDistributionPlot.py
  validmind/unit_metrics/classification/sklearn/ROC_AUC.py
  validmind/utils.py
Labels: internal

#161 Fixes to multiple tests
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/OverfitDiagnosis.py
  validmind/tests/model_validation/sklearn/PrecisionRecallCurve.py
  validmind/tests/model_validation/sklearn/RobustnessDiagnosis.py
  validmind/vm_models/dataset/dataset.py
Labels: internal

#163 Update shap to 0.44.1
  poetry.lock
  pyproject.toml
  validmind/__version__.py
Labels: internal

#165 fix: [sc-5827] Let User Pass a `task` Attribute To Indicate Classification or Regression
  pyproject.toml
  validmind/__version__.py
  validmind/client.py
  validmind/tests/model_validation/sklearn/OverfitDiagnosis.py
  validmind/vm_models/dataset/utils.py
  validmind/vm_models/model.py
Labels: bug, internal

#166 [SC-5784] Fix errors in unit metrics notebook
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/images/composite-metric-in-template-preview.png
  notebooks/images/selecting-composite-metric.png
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: bug, internal

#168 [SC-5838] PipelineModel and ragas fixes
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/client.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
  validmind/tests/model_validation/ragas/Faithfulness.py
Labels: bug, internal

#169 John6797/sc 5851/add regression support to robustness diagnosis
  pyproject.toml
  validmind/__version__.py
  validmind/tests/__types__.py
  validmind/tests/model_validation/sklearn/OverfitDiagnosis.py
  validmind/tests/model_validation/sklearn/RobustnessDiagnosis.py
Labels: enhancement, internal

#170 fix: use dict instead of df for test result in robustness diagnosis
  validmind/tests/model_validation/sklearn/RobustnessDiagnosis.py
Labels: bug, internal

#172 John/upgrade robustness to plotly
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/RobustnessDiagnosis.py
Labels: enhancement, internal

#173 Update LLM notebooks
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#177 [SC-5932] Replace accessing features in tests using parameters and instead use the feature columns
  pyproject.toml
  tests/test_run_all_tests.py
  validmind/__version__.py
  validmind/tests/data_validation/ANOVAOneWayTable.py
  validmind/tests/data_validation/BivariateFeaturesBarPlots.py
  validmind/tests/data_validation/BivariateHistograms.py
  validmind/tests/data_validation/BivariateScatterPlots.py
  validmind/tests/data_validation/ChiSquaredFeaturesTable.py
  validmind/tests/data_validation/FeatureTargetCorrelationPlot.py
  validmind/tests/data_validation/HeatmapFeatureCorrelations.py
  validmind/tests/data_validation/MissingValuesRisk.py
  validmind/tests/data_validation/PearsonCorrelationMatrix.py
  validmind/tests/data_validation/ScatterPlot.py
  validmind/vm_models/dataset/dataset.py
Labels: bug, internal, chore

#178 Refactor add_test_description script
  README.md
  pyproject.toml
  scripts/add_test_description.py
  validmind/__version__.py
  validmind/tests/__types__.py
  validmind/tests/data_validation/BivariateScatterPlots.py
  validmind/tests/ongoing_monitoring/FeatureDrift.py
  validmind/tests/ongoing_monitoring/PredictionAcrossEachFeature.py
  validmind/tests/ongoing_monitoring/PredictionCorrelation.py
  validmind/tests/ongoing_monitoring/TargetPredictionDistributionPlot.py
Labels: internal

#176 First-Class Support for Unit Metrics (Phase 1)
  notebooks/how_to/run_unit_metrics.ipynb
  validmind/ai/test_descriptions.py
  validmind/api_client.py
  validmind/client.py
  validmind/tests/decorator.py
  validmind/tests/run.py
  validmind/unit_metrics/__init__.py
  validmind/unit_metrics/classification/Accuracy.py
  validmind/unit_metrics/classification/F1.py
  validmind/unit_metrics/classification/Precision.py
  validmind/unit_metrics/classification/ROC_AUC.py
  validmind/unit_metrics/classification/Recall.py
  validmind/unit_metrics/regression/AdjustedRSquaredScore.py
  validmind/unit_metrics/regression/GiniCoefficient.py
  validmind/unit_metrics/regression/HuberLoss.py
  validmind/unit_metrics/regression/KolmogorovSmirnovStatistic.py
  validmind/unit_metrics/regression/MeanAbsoluteError.py
  validmind/unit_metrics/regression/MeanAbsolutePercentageError.py
  validmind/unit_metrics/regression/MeanSquaredError.py
  validmind/unit_metrics/regression/QuantileLoss.py
  validmind/unit_metrics/regression/RSquaredScore.py
  validmind/unit_metrics/regression/RootMeanSquaredError.py
  validmind/unit_metrics/regression/sklearn/MeanSquaredError.py
  validmind/vm_models/test/result_wrapper.py
Labels: enhancement, internal

#179 Remove RAGAS Scores Tables
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/tests/decorator.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/Faithfulness.py
Labels: bug, internal

#181 Edited model validation embeddings `StabilityAnalysis.py`
  validmind/tests/model_validation/embeddings/StabilityAnalysis.py
Labels: internal
