Repository validmind/validmind-library, pull requests merged in 2024-04, with the labels that each got.

#21 Improvements to create_new_test
  notebooks/code_sharing/probability_of_default/credit_risk_scorecard_validation_demo.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  poetry.lock
  pyproject.toml
  scripts/__init__.py
  scripts/create_new_test.py
  scripts/test_templates/ThresholdTest.py
  scripts/test_templates/__init__.py
  scripts/test_templates/metric.py
  validmind/tests/data_validation/PiTCreditScoresHistogram.py
  validmind/tests/data_validation/TargetRateBarPlots.py
  validmind/tests/model_validation/statsmodels/ADF.py
  validmind/tests/model_validation/statsmodels/ResidualsVisualInspection.py
  validmind/utils.py
Labels: enhancement

#30 Improvements when using different models
  pyproject.toml
  validmind/__version__.py
  validmind/errors.py
  validmind/models/huggingface.py
  validmind/models/pytorch.py
  validmind/models/sklearn.py
  validmind/tests/model_validation/sklearn/ClassifierPerformance.py
  validmind/tests/model_validation/sklearn/SHAPGlobalImportance.py
  validmind/tests/model_validation/sklearn/TrainingTestDegradation.py
Labels: internal

#29 Custom Metric Function Decorator
  notebooks/code_samples/custom_tests/external_test_providers.ipynb
  notebooks/code_samples/custom_tests/implementing_custom_tests.ipynb
  notebooks/how_to/implementing_custom_tests.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/images/btc-price-custom-metric.png
  notebooks/images/hyperparameters-custom-metric.png
  notebooks/images/image-in-custom-metric.png
  notebooks/images/insert-test-driven-block-custom.png
  notebooks/images/insert-test-driven-block.png
  notebooks/images/multiple-tables-plots-custom-metric.png
  notebooks/images/parameterized-custom-metric.png
  notebooks/images/selecting-composite-metric.png
  pyproject.toml
  validmind/__init__.py
  validmind/__version__.py
  validmind/api_client.py
  validmind/tests/__init__.py
  validmind/tests/decorator.py
  validmind/vm_models/figure.py
Labels: enhancement

#32 John6797/sc 3864/fix failing integration tests
  pyproject.toml
  scripts/run_e2e_notebooks.py
  validmind/__version__.py
Labels: bug, internal

#33 Bug fixes
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/DatasetDescription.py
  validmind/tests/data_validation/nlp/StopWords.py
  validmind/tests/model_validation/statsmodels/RegressionModelsPerformance.py
  validmind/tests/prompt_validation/ai_powered_test.py
  validmind/unit_metrics/composite.py
  validmind/unit_metrics/sklearn/classification/Accuracy.py
  validmind/unit_metrics/sklearn/classification/F1.py
  validmind/unit_metrics/sklearn/classification/Precision.py
  validmind/unit_metrics/sklearn/classification/ROC_AUC.py
  validmind/unit_metrics/sklearn/classification/Recall.py
Labels: internal

#34 Offline predictions for sentiment analysis and summarization
  notebooks/code_samples/nlp_and_llm/datasets/cnn_dailymail_100_with_predictions.csv
  notebooks/code_samples/nlp_and_llm/datasets/cnn_dailymail_500_with_predictions.csv
  notebooks/code_samples/nlp_and_llm/datasets/sentiments_with_predictions.csv
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#37 [SC-3805] Improvements to summarization template and demo notebook
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  poetry.lock
  pyproject.toml
  validmind/datasets/nlp/__init__.py
  validmind/datasets/nlp/cnn_dailymail.py
  validmind/datasets/nlp/datasets/cnn_dailymail_100_with_predictions.csv
  validmind/datasets/nlp/datasets/cnn_dailymail_500_with_predictions.csv
  validmind/datasets/nlp/datasets/sentiments_with_predictions.csv
  validmind/tests/data_validation/nlp/TextDescription.py
  validmind/tests/model_validation/MeteorScore.py
  validmind/tests/model_validation/RegardHistogram.py
  validmind/tests/model_validation/RegardScore.py
  validmind/tests/model_validation/RougeMetrics.py
  validmind/tests/model_validation/SelfCheckNLIScore.py
  validmind/tests/model_validation/embeddings/DescriptiveAnalytics.py
  validmind/unit_metrics/regression/GiniCoefficient.py
  validmind/unit_metrics/regression/HuberLoss.py
  validmind/unit_metrics/regression/KolmogorovSmirnovStatistic.py
  validmind/unit_metrics/regression/MeanAbsolutePercentageError.py
  validmind/unit_metrics/regression/MeanBiasDeviation.py
  validmind/unit_metrics/regression/QuantileLoss.py
  validmind/unit_metrics/regression/sklearn/AdjustedRSquaredScore.py
  validmind/unit_metrics/regression/sklearn/MeanAbsoluteError.py
  validmind/unit_metrics/regression/sklearn/MeanSquaredError.py
  validmind/unit_metrics/regression/sklearn/RSquaredScore.py
  validmind/unit_metrics/regression/sklearn/RootMeanSquaredError.py
  validmind/vm_models/dataset.py
Labels: internal

#31 John6797/sc 3787/poc auto generate test result descriptions
  validmind/ai.py
  validmind/unit_metrics/composite.py
  validmind/utils.py
  validmind/vm_models/figure.py
  validmind/vm_models/test/metric.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test/threshold_test.py
Labels: enhancement, DO NOT MERGE

#39 Improve use case and data description in notebook
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
Labels: internal

#42 Don't Log Figures in Batches
  pyproject.toml
  tests/test_api_client.py
  validmind/__version__.py
  validmind/api_client.py
Labels: internal

#47 [SC 4057] Add residuals plot test for regression models
  scripts/add_test_description.py
  validmind/tests/data_validation/FeatureTargetCorrelationPlot.py
  validmind/tests/data_validation/ScatterPlot.py
  validmind/tests/model_validation/RegressionResidualsPlot.py
Labels: internal

#49 Passing `VMModel` instead of `VMModel.input_id` to `VMDataset` methods
  notebooks/code_samples/custom_tests/implementing_custom_tests.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/ROCCurve.py
  validmind/tests/model_validation/statsmodels/CumulativePredictionProbabilities.py
  validmind/tests/model_validation/statsmodels/GINITable.py
  validmind/tests/model_validation/statsmodels/PredictionProbabilitiesHistogram.py
  validmind/vm_models/dataset.py
Labels: internal

#51 Fix prediction probabilities
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/dataset.py
Labels: bug, internal

#52 [SC-3423] Improvements to credit risk scorecard notebook
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/FeaturesAUC.py
  validmind/tests/model_validation/statsmodels/CumulativePredictionProbabilities.py
  validmind/tests/model_validation/statsmodels/PredictionProbabilitiesHistogram.py
  validmind/tests/model_validation/statsmodels/RegressionPermutationFeatureImportance.py
  validmind/tests/model_validation/statsmodels/ScorecardHistogram.py
Labels: internal

#48 John6797/sc 3881/support for metadata in new metric decorator
  notebooks/code_samples/custom_tests/external_test_providers.ipynb
  notebooks/code_sharing/external_tests/end_to_end_isolation_forest_external.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  pyproject.toml
  scripts/run_e2e_notebooks.py
  validmind/__init__.py
  validmind/__version__.py
  validmind/tests/__init__.py
  validmind/tests/__types__.py
  validmind/tests/decorator.py
  validmind/tests/model_validation/FeaturesAUC.py
  validmind/tests/model_validation/statsmodels/RegressionPermutationFeatureImportance.py
  validmind/tests/test_providers.py
  validmind/unit_metrics/classification/sklearn/Accuracy.py
  validmind/unit_metrics/classification/sklearn/F1.py
  validmind/unit_metrics/classification/sklearn/Precision.py
  validmind/unit_metrics/classification/sklearn/ROC_AUC.py
  validmind/unit_metrics/classification/sklearn/Recall.py
  validmind/unit_metrics/composite.py
  validmind/unit_metrics/regression/GiniCoefficient.py
  validmind/unit_metrics/regression/HuberLoss.py
  validmind/unit_metrics/regression/KolmogorovSmirnovStatistic.py
  validmind/unit_metrics/regression/MeanAbsolutePercentageError.py
  validmind/unit_metrics/regression/MeanBiasDeviation.py
  validmind/unit_metrics/regression/QuantileLoss.py
  validmind/unit_metrics/regression/sklearn/AdjustedRSquaredScore.py
  validmind/unit_metrics/regression/sklearn/MeanAbsoluteError.py
  validmind/unit_metrics/regression/sklearn/MeanSquaredError.py
  validmind/unit_metrics/regression/sklearn/RSquaredScore.py
  validmind/unit_metrics/regression/sklearn/RootMeanSquaredError.py
Labels: enhancement

#53 Hotfix for Integration Tests Script
  scripts/run_e2e_notebooks.py
Labels: bug, internal

#58 Couple of Bug Fixes
  notebooks/how_to/explore_tests.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/test_suites/__init__.py
  validmind/tests/__init__.py
  validmind/tests/decorator.py
  validmind/vm_models/test/test.py
  validmind/vm_models/test_suite/test_suite.py
Labels: bug, internal

#57 Edited credit score notebook
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
Labels: internal

#50 New introductory notebook for model developers
  .gitignore
  notebooks/images/high-pearson-correlation-block.png
  notebooks/images/insert-test-driven-block-correlations.png
  notebooks/images/insert-test-driven-block-custom-confusion-matrix.png
  notebooks/images/my_tests_directory.png
  notebooks/images/selecting-high-pearson-correlation-test.png
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: enhancement

#61 Cachafla/reduce shap sample
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/SHAPGlobalImportance.py
Labels: internal

#64 Small notebook fixes
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/how_to/run_a_test.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  scripts/run_e2e_notebooks.py
Labels: internal
