Repository validmind/validmind-library, pull requests merged in 2024-10, with the labels that each got.

#200 Fix PyPI publish
  .github/workflows/pypi.yaml
Labels: internal

#202 John6797/sc 6723/step 1 get rid of test runs
  Makefile
  pyproject.toml
  tests/test_api_client.py
  tests/test_api_client_sync.py
  validmind/__version__.py
  validmind/api_client.py
  validmind/errors.py
Labels: internal, refactor

#203 Removed references to projects in Jupyter Notebooks
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_sharing/llm/rag_rfp_answer_generation.ipynb
  notebooks/code_sharing/llm/rag_rfp_answer_generation_langchain.ipynb
  notebooks/code_sharing/test_configuration_updates_demo.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#204 Quick fixes for ongoing monitoring
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#206 fix: fixing issue with missing dependency
  .github/workflows/python.yaml
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  validmind/errors.py
  validmind/tests/data_validation/ProtectedClassesCombination.py
  validmind/tests/data_validation/ProtectedClassesDisparity.py
  validmind/tests/data_validation/ProtectedClassesThresholdOptimizer.py
  validmind/tests/load.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextUtilization.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/NoiseSensitivity.py
Labels: enhancement, internal

#207 Hotfix: Add standardized handling for missing dependencies
  .github/workflows/python.yaml
  README.md
  pyproject.toml
  validmind/__version__.py
  validmind/errors.py
  validmind/tests/data_validation/ProtectedClassesCombination.py
  validmind/tests/data_validation/ProtectedClassesDisparity.py
  validmind/tests/data_validation/ProtectedClassesThresholdOptimizer.py
  validmind/tests/load.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextUtilization.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/NoiseSensitivity.py
Labels: bug, enhancement, internal

#208 fix: fixing dependency issues in workflow files and doing some cleanup
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  .github/workflows/pypi.yaml
  .github/workflows/python.yaml
  README.md
  poetry.lock
  pyproject.toml
  scripts/run_e2e_notebooks.py
  tests/test_api_client.py
  tests/test_api_client_sync.py
  tests/test_framework_init.py
  tests/test_full_suite.py
  tests/test_full_suite_nb.py
  validmind/__init__.py
  validmind/__version__.py
  validmind/api_client.py
  validmind/client_config.py
  validmind/errors.py
  validmind/vm_models/test/result_wrapper.py
Labels: internal, chore

#214 [SC-7262] Update RAG documentation demo notebook
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: enhancement, internal

#212 Added Upgrade ValidMind instructions to Jupyter Notebooks
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#153 [SC 5606] POC for the option pricer model
  notebooks/code_sharing/capital_markets/OptionPricer.ipynb
  notebooks/code_sharing/capital_markets/option_pricing_models_vm.ipynb
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models.ipynb
Labels: enhancement, internal, highlight

#217 Prod 2.5.19 to main
  .github/workflows/prod_patches_to_main.yaml
  .github/workflows/python.yaml
  pyproject.toml
Labels: internal
