Repository validmind/validmind-library, pull requests merged in 2024-09, with the labels that each got.

#183 John6797/hotfix/correctly log metric with only figures
  pyproject.toml
  validmind/__version__.py
  validmind/tests/decorator.py
  validmind/unit_metrics/__init__.py
Labels: bug, internal

#182 Feat: Support PNG Images for Test Results Description Generation
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/figure.py
Labels: enhancement, internal

#184 Removed documentation projects from JN
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/support_polars_dataset.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
Labels: internal

#186 John6797/sc 6492/add support for unit metric template blocks
  pyproject.toml
  validmind/__version__.py
  validmind/template.py
Labels: bug, internal

#187 Ability to disable test descriptions on the developer framework via feature flags
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/api_client.py
  validmind/client_config.py
  validmind/tests/model_validation/ragas/utils.py
  validmind/tests/prompt_validation/ai_powered_test.py
Labels: internal

#192 Fix: Clean Docs Build Folder Before Regenerating
  Makefile
Labels: bug, internal

#190 Fix Broken RAGAS Test and Add New
  .github/workflows/python.yaml
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  poetry.lock
  pyproject.toml
  validmind/__version__.py
  validmind/tests/__types__.py
  validmind/tests/data_validation/ChiSquaredFeaturesTable.py
  validmind/tests/data_validation/nlp/TextDescription.py
  validmind/tests/model_validation/ContextualRecall.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextUtilization.py
  validmind/tests/model_validation/ragas/NoiseSensitivity.py
  validmind/tests/model_validation/sklearn/FeatureImportance.py
  validmind/tests/model_validation/sklearn/RegressionR2Square.py
  validmind/tests/model_validation/statsmodels/PredictionProbabilitiesHistogram.py
  validmind/tests/model_validation/statsmodels/RegressionCoeffs.py
Labels: bug, internal

#195 Replaced static links to prod UI with docs links
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#193 [SC-6552] Fix tests with no outputs
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  pyproject.toml
  tests/run_test_utils.py
  validmind/__version__.py
  validmind/tests/data_validation/BoxPierce.py
  validmind/tests/data_validation/JarqueBera.py
  validmind/tests/data_validation/LJungBox.py
  validmind/tests/data_validation/RunsTest.py
  validmind/tests/data_validation/ShapiroWilk.py
  validmind/tests/model_validation/statsmodels/DurbinWatsonTest.py
Labels: bug, internal
