Repository validmind/validmind-library, pull requests merged in 2024-07, with the labels that each got.

#128 Cachafla/fix vr template preview
  pyproject.toml
  validmind/__version__.py
  validmind/template.py
Labels: internal

#127 [SC-5175] Enhance add extra column to support 2d arrays
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/TabularDescriptionTables.py
  validmind/vm_models/dataset/dataset.py
Labels: enhancement

#129 John6797/sc-4068/add-support-for-model-or-project-argument
  Makefile
  pyproject.toml
  tests/test_api_client.py
  tests/test_api_client_sync.py
  tests/test_framework_init.py
  validmind/__version__.py
  validmind/api_client.py
  validmind/tests/run.py
  validmind/vm_models/test_suite/summary.py
Labels: internal, chore

#130 [SC-5207] Fix `_add_column` integration test
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/dataset/dataset.py
Labels: bug, internal

#131 Fixed broken docs links in `.ipynb`
  README.md
  notebooks/README.md
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/code_sharing/support_polars_dataset.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/explore_tests.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#132 PR#131 edit — Missed some #anchor links, fixed now
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/support_polars_dataset.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#135 Prod -> Main
  validmind/template.py
Labels: internal

#137 Testing support for more tests
  notebooks/code_samples/nlp_and_llm/datasets/cnn_dailymail_100_with_predictions.csv
  notebooks/code_samples/nlp_and_llm/datasets/cnn_dailymail_500_with_predictions.csv
  poetry.lock
  pyproject.toml
  tests/run_test_utils.py
  tests/test_run_all_tests.py
  validmind/__version__.py
  validmind/datasets/nlp/cnn_dailymail.py
  validmind/datasets/nlp/datasets/cnn_dailymail_100_with_predictions.csv
  validmind/datasets/nlp/datasets/cnn_dailymail_500_with_predictions.csv
  validmind/models/huggingface.py
  validmind/tests/model_validation/embeddings/ClusterDistribution.py
  validmind/tests/model_validation/embeddings/CosineSimilarityDistribution.py
  validmind/tests/model_validation/embeddings/DescriptiveAnalytics.py
  validmind/tests/model_validation/embeddings/EmbeddingsVisualization2D.py
  validmind/tests/model_validation/embeddings/StabilityAnalysis.py
  validmind/tests/model_validation/embeddings/StabilityAnalysisTranslation.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
  validmind/tests/model_validation/sklearn/HyperParametersTuning.py
Labels: internal

#140 [SC-5466] Exclude categorical and binary features from outlier tests
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/IQROutliersBarPlot.py
  validmind/tests/data_validation/IQROutliersTable.py
Labels: bug, internal

#141 fix: add openai as core dependency
  poetry.lock
  pyproject.toml
Labels: bug, internal

#143 Missed some Learn more ... Model documentation links
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
Labels: internal

#144 Generalize support for comparison tests
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: internal

#146 Hotfix: Remove `openai` from `all` extras group
  poetry.lock
  pyproject.toml
  validmind/__version__.py
Labels: bug, internal

#148 Hotfix/dependency issues
  poetry.lock
  pyproject.toml
  validmind/__version__.py
  validmind/html_templates/content_blocks.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/utils.py
Labels: bug, internal

#149 Fix `Text` type casting
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/DatasetDescription.py
Labels: internal
