Repository validmind/validmind-library, pull requests merged in 2024-03, with the labels that each got.

#5 Updating numpy version to ^1.23.3 and shap to ^0.42.0
  poetry.lock
  pyproject.toml
Labels: internal

#6 Fixes to ensure all public notebooks run end to end
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/how_to/implementing_custom_tests.ipynb
  notebooks/how_to/run_a_test_suite.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/RegressionModelsPerformanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionR2Square.py
  validmind/vm_models/dataset.py
  validmind/vm_models/test_context.py
  validmind/vm_models/test_suite/runner.py
Labels: internal

#3 [Cherry Pick] Use input_id to track inputs being accessed
  Makefile
  pyproject.toml
  tests/test_validmind_tests.py
  validmind/__version__.py
  validmind/client.py
  validmind/vm_models/dataset.py
  validmind/vm_models/model.py
  validmind/vm_models/test_context.py
Labels: internal

#7 Update main branches with fixes from release-v1 branch (1.27.4)
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  .github/workflows/python.yaml
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/how_to/implementing_custom_tests.ipynb
  notebooks/how_to/run_a_test_suite.ipynb
  poetry.lock
  pyproject.toml
  validmind/tests/model_validation/sklearn/RegressionModelsPerformanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionR2Square.py
  validmind/vm_models/test_suite/runner.py
Labels: internal

#8 Remove use of np.object
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/TabularCategoricalBarPlots.py
  validmind/vm_models/dataset.py
Labels: internal

#9 Prod 1.27.5
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/TabularCategoricalBarPlots.py
  validmind/vm_models/dataset.py
Labels: internal

#10 Fix references to documentation project in Jupyter notebooks
  notebooks/code_samples/custom_tests/external_test_providers_demo.ipynb
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/external_tests/end_to_end_isolation_forest_external.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/llm/foundation_models_summarization_high_code.ipynb
  notebooks/code_sharing/llm/hugging_face_text_continuation_poc.ipynb
  notebooks/code_sharing/llm/summarization_bias_toxicity_safety_poc.ipynb
  notebooks/code_sharing/nlp/nlp_sentiment_analysis_demo.ipynb
  notebooks/code_sharing/notebook-template.ipynb
  notebooks/code_sharing/probability_of_default/credit_risk_scorecard_validation_demo.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  notebooks/code_sharing/test_configuration_updates_demo.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/configure_parameters_demo.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/implementing_custom_tests.ipynb
  notebooks/how_to/run_a_test.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
Labels: internal

#11 Fix some cells with invalid syntax
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#1 Apply changes from juan5508/sc-3259/Create-Metric-V2-class
  notebooks/how_to/run_unit_metrics.ipynb
  poetry.lock
  pyproject.toml
  validmind/__init__.py
  validmind/client.py
  validmind/unit_metrics/__init__.py
  validmind/unit_metrics/sklearn/classification/Accuracy.py
  validmind/unit_metrics/sklearn/classification/F1.py
  validmind/unit_metrics/sklearn/classification/Precision.py
  validmind/unit_metrics/sklearn/classification/ROC_AUC.py
  validmind/unit_metrics/sklearn/classification/Recall.py
  validmind/vm_models/__init__.py
  validmind/vm_models/test/unit_metric.py
Labels: enhancement

#12 Ensure all notebooks run end to end with new input/predictions syntax
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/how_to/run_a_test.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  scripts/run_e2e_notebooks.py
  validmind/__init__.py
  validmind/client.py
  validmind/datasets/classification/customer_churn.py
  validmind/models/foundation.py
  validmind/tests/data_validation/IQROutliersBarPlot.py
  validmind/tests/model_validation/sklearn/PrecisionRecallCurve.py
  validmind/tests/model_validation/sklearn/ROCCurve.py
  validmind/tests/prompt_validation/Robustness.py
  validmind/unit_metrics/__init__.py
  validmind/unit_metrics/sklearn/classification/Accuracy.py
  validmind/unit_metrics/sklearn/classification/F1.py
  validmind/unit_metrics/sklearn/classification/Precision.py
  validmind/unit_metrics/sklearn/classification/ROC_AUC.py
  validmind/unit_metrics/sklearn/classification/Recall.py
  validmind/vm_models/__init__.py
  validmind/vm_models/dataset.py
  validmind/vm_models/test/unit_metric.py
Labels: internal

#13 [SC 3406] Follow up fix notebooks and tests after merging
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/how_to/configure_parameters_demo.ipynb
  notebooks/how_to/run_a_test.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
Labels: internal

#15 Update release_notes_check.yamlRun release notes check only if not in draft mode
  .github/workflows/release_notes_check.yaml
Labels: internal

#16 Update references to documentation projects on the main branch
  docs/_build/validmind.html
  notebooks/code_samples/custom_tests/external_test_providers_demo.ipynb
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/external_tests/end_to_end_isolation_forest_external.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/llm/foundation_models_summarization_high_code.ipynb
  notebooks/code_sharing/llm/hugging_face_text_continuation_poc.ipynb
  notebooks/code_sharing/llm/summarization_bias_toxicity_safety_poc.ipynb
  notebooks/code_sharing/nlp/nlp_sentiment_analysis_demo.ipynb
  notebooks/code_sharing/notebook-template.ipynb
  notebooks/code_sharing/probability_of_default/credit_risk_scorecard_validation_demo.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  notebooks/code_sharing/test_configuration_updates_demo.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/configure_parameters_demo.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/implementing_custom_tests.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_a_test.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_with_config.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  pyproject.toml
  validmind/datasets/classification/customer_churn.py
  validmind/input_registry.py
  validmind/tests/data_validation/TabularCategoricalBarPlots.py
  validmind/vm_models/dataset.py
  validmind/vm_models/test_context.py
Labels: internal

#20 Hotfix/fix result log method
  notebooks/code_sharing/probability_of_default/credit_risk_scorecard_validation_demo.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test/test.py
  validmind/vm_models/test_suite/test.py
Labels: bug, internal

#19 Hotfix/fix log method
  notebooks/code_sharing/probability_of_default/credit_risk_scorecard_validation_demo.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test/test.py
  validmind/vm_models/test_suite/test.py
Labels: bug, internal

#22 Cachafla/v2 fixes
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_with_config.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/datasets/classification/customer_churn.py
  validmind/utils.py
Labels: internal

#25 Fix some broken tests
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/PiTCreditScoresHistogram.py
  validmind/tests/data_validation/TargetRateBarPlots.py
  validmind/tests/model_validation/statsmodels/ADF.py
  validmind/tests/model_validation/statsmodels/ResidualsVisualInspection.py
Labels: internal

#24 John6797/sc 3667/fix missing dependency
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/test/output_template.py
Labels: bug

#26 Add abstract definitions for VMDataset
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/dataset.py
Labels: internal

#18 John6797/sc 3412/ability to compose a metric by combining
  notebooks/how_to/images/insert-test-driven-block.png
  notebooks/how_to/images/selecting-composite-metric.png
  notebooks/how_to/run_unit_metrics.ipynb
  tests/test_api_client.py
  validmind/api_client.py
  validmind/tests/__init__.py
  validmind/unit_metrics/__init__.py
  validmind/unit_metrics/composite.py
  validmind/unit_metrics/sklearn/classification/Accuracy.py
  validmind/unit_metrics/sklearn/classification/F1.py
  validmind/unit_metrics/sklearn/classification/Precision.py
  validmind/unit_metrics/sklearn/classification/ROC_AUC.py
  validmind/unit_metrics/sklearn/classification/Recall.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test/test.py
  validmind/vm_models/test_context.py
  validmind/vm_models/test_suite/runner.py
  validmind/vm_models/test_suite/test.py
Labels: enhancement

#27 Support adding new extra columns on the fly
  validmind/unit_metrics/composite.py
  validmind/vm_models/dataset.py
  validmind/vm_models/test/result_wrapper.py
Labels: enhancement

#28 John6797/fix python dependencies
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_sharing/llm/foundation_models_summarization_high_code.ipynb
  poetry.lock
  pyproject.toml
  tests/test_full_suite.py
  tests/test_full_suite_nb.py
  validmind/datasets/classification/customer_churn.py
Labels: bug, enhancement
