Repository validmind/validmind-library, pull requests merged in 2024-11, with the labels that each got.

#220 Cachafla/sc 7304/fix seaborn warnings on overfit and weakness
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/OverfitDiagnosis.py
  validmind/tests/model_validation/sklearn/SHAPGlobalImportance.py
  validmind/tests/model_validation/sklearn/WeakspotsDiagnosis.py
Labels: internal

#223 Hotfix prod/broken ragas version
  poetry.lock
  pyproject.toml
  validmind/__version__.py
Labels: bug, internal

#224 fix: threshold test comparisons not working with param_grid changes
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: bug, internal

#167 FEAT: run custom R tests
  notebooks/code_sharing/r/r_custom_tests.Rmd
  notebooks/code_sharing/r/r_customer_churn_demo.Rmd
  notebooks/code_sharing/r/r_customer_churn_demo_xgboost.Rmd
  r/validmind/DESCRIPTION
  r/validmind/NAMESPACE
  r/validmind/R/custom_tests.R
  r/validmind/R/platform.R
  r/validmind/README.md
  r/validmind/man/build_r_plotly.Rd
  r/validmind/man/display_report.Rd
  r/validmind/man/print_summary_tables.Rd
  r/validmind/man/process_result.Rd
  r/validmind/man/register_custom_test.Rd
  r/validmind/man/run_custom_test.Rd
  r/validmind/man/save_model.Rd
  r/validmind/man/summarize_metric_result.Rd
  r/validmind/man/summarize_result.Rd
  r/validmind/man/summarize_test_result.Rd
  r/validmind/man/vm.Rd
  validmind/client.py
Labels: internal

#227 #226: Use system tempdir for R save_model
  r/validmind/R/platform.R
Labels: internal

#219 [SC7201] Spike POC for the option pricer model using quantlib
  .github/workflows/python.yaml
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
  poetry.lock
  pyproject.toml
  validmind/tests/ongoing_monitoring/TargetPredictionDistributionPlot.py
  validmind/tests/run.py
Labels: internal

#229 fix: run integration tests on large runners
  .github/workflows/integration.yaml
Labels: internal, chore

#231 [SC-7379] Updates and small fixes to NLP data validation tests
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/nlp/CommonWords.py
  validmind/tests/data_validation/nlp/PolarityAndSubjectivity.py
  validmind/tests/data_validation/nlp/Punctuations.py
  validmind/tests/data_validation/nlp/StopWords.py
Labels: bug, internal, chore

#234 Ignore some files when running `make docs` on Mac
  Makefile
Labels: internal

#235 Python docs intro adjust
  pyproject.toml
  validmind/__init__.py
  validmind/__version__.py
Labels: internal

#236 Bye old repo 39 4 ur service
  README.md
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_tests_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  r/validmind/DESCRIPTION
  r/validmind/README.md
  validmind/__version__.py
Labels: internal

#232 [SC 7399] Serialize date, time, datetime and Date objects to log test results
  validmind/utils.py
Labels: bug, internal

#238 Run docs on Ubuntu large
  .github/workflows/docs.yaml
Labels: internal

#237 [SC 7431] Update the custom tests names in the option pricer models notebooks
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
Labels: internal

#239 Updated logos in python docs & readme
  Makefile
  README.md
  pyproject.toml
  validmind/__version__.py
Labels: internal

#245 John6797/fix bugs from refactor
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
  validmind/vm_models/figure.py
Labels: bug, internal

#251 Updated "Get your code snippet" section for relevant notebooks
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/capital_markets/option_pricing_models_vm.ipynb
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_sharing/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/credit_risk/assign_prediction_probabilities.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/insurance_mortality/insurance_validation_demo.ipynb
  notebooks/code_sharing/llm/vendor_contract_agent/genai_vendor_contract_agent_usecase_poc.ipynb
  notebooks/code_sharing/market_basket_analysis/mba_poc.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/output_templates/customizing_tests_with_output_templates.ipynb
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/code_sharing/test_configuration_updates_demo.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#253 [SC-7605] Fix: input data mutation in PSI test affecting other tests during documentation suite execution
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/PopulationStabilityIndex.py
Labels: bug, internal
