Repository validmind/validmind-library, pull requests merged in 2024-05, with the labels that each got.

#65 Edited how to run dataset based tests notebook
  notebooks/README.md
  notebooks/archive/configure_test_parameters.ipynb
  notebooks/how_to/how_to_run_tests/1_how_to_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
Labels: internal

#67 Support for external models
  tests/test_client.py
  tests/test_dataset.py
  validmind/client.py
  validmind/tests/model_validation/sklearn/SHAPGlobalImportance.py
  validmind/vm_models/dataset.py
  validmind/vm_models/model.py
Labels: enhancement

#70 Fix prediction probabilities
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/dataset.py
Labels: bug, internal

#56 [POC] RAG pipeline for RFP answer generation with LangChain and RAGAS
  .gitignore
  notebooks/code_sharing/llm/datasets/rag/rag_evaluation_dataset_01.csv
  notebooks/code_sharing/llm/datasets/rag/rag_evaluation_dataset_02.csv
  notebooks/code_sharing/llm/datasets/rag/rag_evaluation_dataset_03.csv
  notebooks/code_sharing/llm/datasets/rag/rag_evaluation_results.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_existing_questions_client_1.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_existing_questions_client_2.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_existing_questions_client_3.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_existing_questions_client_4.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_existing_questions_client_5.csv
  notebooks/code_sharing/llm/datasets/rag/rfp_new_questions_client_100.csv
  notebooks/code_sharing/llm/rag_rfp_answer_generation_langchain.ipynb
  notebooks/code_sharing/llm/rag_rfp_answer_genertion.ipynb
  notebooks/code_sharing/llm/rag_rfp_question_similarity.ipynb
Labels: internal, DO NOT MERGE

#68 [SC-4213] Create a notebook with LlamaIndex as the RAG pipeline coordinator
  notebooks/code_sharing/llm/rag_llamaindex.ipynb
Labels: internal

#69 [SC 4212] Build end to end notebook that uses langchain
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
  validmind/datasets/llm/rag/__init__.py
  validmind/datasets/llm/rag/datasets/rfp_existing_questions_client_1.csv
  validmind/datasets/llm/rag/datasets/rfp_existing_questions_client_2.csv
  validmind/datasets/llm/rag/datasets/rfp_existing_questions_client_3.csv
  validmind/datasets/llm/rag/datasets/rfp_existing_questions_client_4.csv
  validmind/datasets/llm/rag/datasets/rfp_existing_questions_client_5.csv
  validmind/datasets/llm/rag/rfp.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
Labels: internal

#72 Fix rendering risk assessment blocks
  pyproject.toml
  validmind/__version__.py
  validmind/template.py
Labels: internal

#73 fixing issue that was causing integration tests to fail
  validmind/unit_metrics/__init__.py
Labels: bug, internal

#74 Fix notebook and ragas tests
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
Labels: internal

#75 [SC-4213] Create embedding metrics
  notebooks/code_sharing/llm/datasets/rag/vendor_contracts_001_020.csv
  notebooks/code_sharing/llm/datasets/rag/vendor_contracts_021_040.csv
  notebooks/code_sharing/llm/datasets/rag/vendor_contracts_041_060.csv
  notebooks/code_sharing/llm/datasets/rag/vendor_contracts_questions.csv
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
  notebooks/code_sharing/llm/rag_vendor_contracts_llamaindex.ipynb
  validmind/tests/model_validation/embeddings/CosineSimilarityHeatmap.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceHeatmap.py
  validmind/tests/model_validation/embeddings/PCAComponentsPairwisePlots.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
Labels: internal

#78 [SC 4211] Define and implement required output validation tests for RAG use case
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
  validmind/tests/data_validation/nlp/LanguageDetection.py
  validmind/tests/model_validation/embeddings/PCAComponentsPairwisePlots.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
Labels: internal

#82 RAG Demo Notebook
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
  validmind/client.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/vm_models/model.py
Labels: internal

#79 [SC-4213] RAG with LlamaIndex end to end notebook
  notebooks/code_sharing/llm/rag_vendor_contracts_llamaindex.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/embeddings/CosineSimilarityComparison.py
  validmind/tests/model_validation/embeddings/CosineSimilarityHeatmap.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceComparison.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceHeatmap.py
  validmind/tests/model_validation/embeddings/PCAComponentsPairwisePlots.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
Labels: internal

#83 [SC 4445] Update rag langchain demo notebook
  notebooks/code_sharing/llm/rag_langchain_demo.ipynb
Labels: internal

#77 Initial Framework Support for LLM Agents
  .gitignore
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_sharing/llm/initial_rag_support.ipynb
  notebooks/code_sharing/llm/rag_rfp_answer_generation.ipynb
  notebooks/code_sharing/llm/rag_rfp_answer_generation_langchain.ipynb
  notebooks/code_sharing/llm/rag_rfp_question_similarity.ipynb
  notebooks/code_sharing/llm/vendor_contract_agent/data/contracts.json
  notebooks/code_sharing/llm/vendor_contract_agent/data/vendors.json
  notebooks/code_sharing/llm/vendor_contract_agent/genai_vendor_contract_agent_usecase_poc.ipynb
  notebooks/code_sharing/llm/vendor_contract_agent/tool_definitions/query_database.json
  notebooks/code_sharing/llm/vendor_contract_agent/tool_definitions/search_online.json
  notebooks/code_sharing/llm/vendor_contract_agent/utils.py
  poetry.lock
  pyproject.toml
  scripts/add_test_description.py
  tests/test_api_client.py
  validmind/__version__.py
  validmind/ai.py
  validmind/api_client.py
  validmind/html_templates/__init__.py
  validmind/html_templates/content_blocks.py
  validmind/template.py
  validmind/tests/__init__.py
  validmind/tests/decorator.py
  validmind/tests/model_validation/embeddings/CosineSimilarityComparison.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceComparison.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/utils.py
  validmind/utils.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test_suite/summary.py
Labels: enhancement, internal

#85 Hotfix/predictions bug
  validmind/html_templates/content_blocks.py
  validmind/tests/__init__.py
  validmind/vm_models/dataset/dataset.py
Labels: bug, internal

#86 fixing input tracking for composite metrics
  validmind/unit_metrics/__init__.py
  validmind/unit_metrics/composite.py
Labels: bug, internal

#88 John6797/sc 4573/fix input registration and tracking for foundationmodel
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_sharing/llm/foundation_models_summarization_high_code.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/client.py
  validmind/models/pipeline.py
  validmind/vm_models/model.py
Labels: bug, internal

#84 [SC-4444] Enhancements to NLP model evaluation metrics
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/models/huggingface.py
  validmind/tests/__init__.py
  validmind/tests/model_validation/BertScore.py
  validmind/tests/model_validation/BertScoreAggregate.py
  validmind/tests/model_validation/BleuScore.py
  validmind/tests/model_validation/ContextualRecall.py
  validmind/tests/model_validation/MeteorScore.py
  validmind/tests/model_validation/RegardHistogram.py
  validmind/tests/model_validation/RegardScore.py
  validmind/tests/model_validation/RougeMetrics.py
  validmind/tests/model_validation/RougeMetricsAggregate.py
  validmind/tests/model_validation/RougeScore.py
  validmind/tests/model_validation/SelfCheckNLIScore.py
  validmind/tests/model_validation/TokenDisparity.py
  validmind/tests/model_validation/ToxicityHistogram.py
  validmind/tests/model_validation/ToxicityScore.py
  validmind/utils.py
Labels: enhancement, internal

#91 Fixed broken links in integrate_external_test_providers.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
Labels: internal

#93 Fix add extra columns and other fixes in preview template
  pyproject.toml
  validmind/__version__.py
  validmind/tests/__init__.py
  validmind/vm_models/dataset/dataset.py
Labels: bug, internal

#92 Allow passing section_id and position to result.log()
  tests/test_api_client.py
  tests/test_api_client_sync.py
  validmind/api_client.py
  validmind/errors.py
  validmind/vm_models/test/result_wrapper.py
Labels: enhancement

#94 Enable LLM Descriptions for Function Metric and Composite Metric Results and Fix Support for Markdown Table in Descriptions
  notebooks/how_to/run_unit_metrics.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/ai.py
  validmind/tests/decorator.py
  validmind/unit_metrics/composite.py
  validmind/utils.py
  validmind/vm_models/test/metric.py
  validmind/vm_models/test/threshold_test.py
Labels: bug

#90 Fixed callouts in notebooks
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/customization/customizing_metrics_with_output_templates.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#97 Hotfix: Use correct prefix test descriptions
  pyproject.toml
  validmind/__version__.py
  validmind/ai.py
  validmind/utils.py
  validmind/vm_models/test/threshold_test.py
Labels: bug, internal

#96 FIxed broken link to dev framework docs
  README.md
Labels: internal

#98 Turn on LLM-Generated Descriptions by Default
  notebooks/code_sharing/llm/vendor_contract_agent/utils.py
  pyproject.toml
  tests/test_api_client.py
  validmind/__version__.py
  validmind/ai.py
  validmind/api_client.py
  validmind/logging.py
  validmind/tests/prompt_validation/ai_powered_test.py
  validmind/utils.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test_suite/runner.py
  validmind/vm_models/test_suite/summary.py
  validmind/vm_models/test_suite/test.py
Labels: enhancement

#102 Add support for the ValidMind LLM Service
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_sharing/llm/foundation_models_summarization_high_code.ipynb
  pyproject.toml
  tests/test_full_suite.py
  tests/test_full_suite_nb.py
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/ai/utils.py
  validmind/api_client.py
  validmind/client.py
  validmind/tests/decorator.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/utils.py
  validmind/tests/prompt_validation/Bias.py
  validmind/tests/prompt_validation/Clarity.py
  validmind/tests/prompt_validation/Conciseness.py
  validmind/tests/prompt_validation/Delimitation.py
  validmind/tests/prompt_validation/NegativeInstruction.py
  validmind/tests/prompt_validation/Robustness.py
  validmind/tests/prompt_validation/Specificity.py
  validmind/tests/prompt_validation/ai_powered_test.py
  validmind/unit_metrics/composite.py
  validmind/utils.py
  validmind/vm_models/test/metric.py
  validmind/vm_models/test/result_wrapper.py
  validmind/vm_models/test/threshold_test.py
Labels: enhancement
