Repository validmind/validmind-library, pull requests merged in 2024-06, with the labels that each got.

#104 Various Fixes - Fixes to Ragas Tests, Prompt Validation Tests
  .flake8
  Makefile
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  validmind/ai/test_descriptions.py
  validmind/ai/utils.py
  validmind/client.py
  validmind/models/foundation.py
  validmind/models/function.py
  validmind/models/metadata.py
  validmind/tests/data_validation/HighPearsonCorrelation.py
  validmind/tests/data_validation/SeasonalDecompose.py
  validmind/tests/data_validation/nlp/PolarityAndSubjectivity.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/AnswerRelevance.py
  validmind/tests/model_validation/ragas/AnswerSimilarity.py
  validmind/tests/model_validation/ragas/AspectCritique.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/ContextRelevancy.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/utils.py
  validmind/tests/model_validation/sklearn/ClusterPerformance.py
  validmind/tests/model_validation/sklearn/ClusterPerformanceMetrics.py
  validmind/tests/model_validation/sklearn/ModelsPerformanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionErrors.py
  validmind/tests/model_validation/sklearn/RegressionModelsPerformanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionR2Square.py
  validmind/tests/model_validation/statsmodels/GINITable.py
  validmind/tests/model_validation/statsmodels/PDRatingClassPlot.py
  validmind/tests/prompt_validation/Bias.py
  validmind/tests/prompt_validation/Clarity.py
  validmind/tests/prompt_validation/Conciseness.py
  validmind/tests/prompt_validation/Delimitation.py
  validmind/tests/prompt_validation/NegativeInstruction.py
  validmind/tests/prompt_validation/Robustness.py
  validmind/tests/prompt_validation/Specificity.py
  validmind/tests/prompt_validation/ai_powered_test.py
  validmind/utils.py
  validmind/vm_models/dataset/dataset.py
  validmind/vm_models/dataset/utils.py
  validmind/vm_models/model.py
  validmind/vm_models/test/metric.py
  validmind/vm_models/test/test.py
  validmind/vm_models/test_suite/runner.py
Labels: bug, internal, chore

#103 Fix misspellings of "ValidMind"
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/code_sharing/external_tests/end_to_end_isolation_forest_external.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  tests/test_validmind_tests_module.py
Labels: internal

#105 run_test() integration tests
  pyproject.toml
  tests/run_test_utils.py
  tests/test_run_all_tests.py
  validmind/__version__.py
  validmind/api_client.py
  validmind/test_suites/__init__.py
  validmind/test_suites/regression.py
  validmind/tests/data_validation/DefaultRatesbyRiskBandPlot.py
  validmind/tests/data_validation/HeatmapFeatureCorrelations.py
  validmind/tests/data_validation/IsolationForestOutliers.py
  validmind/tests/data_validation/PiTPDHistogram.py
  validmind/tests/data_validation/ScatterPlot.py
  validmind/tests/data_validation/TabularDateTimeHistograms.py
  validmind/tests/data_validation/WOEBinPlots.py
  validmind/tests/data_validation/WOEBinTable.py
  validmind/tests/data_validation/nlp/CommonWords.py
  validmind/tests/data_validation/nlp/Hashtags.py
  validmind/tests/data_validation/nlp/Mentions.py
  validmind/tests/data_validation/nlp/PolarityAndSubjectivity.py
  validmind/tests/data_validation/nlp/Punctuations.py
  validmind/tests/data_validation/nlp/Sentiment.py
  validmind/tests/data_validation/nlp/TextDescription.py
  validmind/tests/data_validation/nlp/Toxicity.py
  validmind/tests/model_validation/FeaturesAUC.py
  validmind/tests/model_validation/embeddings/CosineSimilarityComparison.py
  validmind/tests/model_validation/embeddings/CosineSimilarityHeatmap.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceComparison.py
  validmind/tests/model_validation/embeddings/EuclideanDistanceHeatmap.py
  validmind/tests/model_validation/embeddings/PCAComponentsPairwisePlots.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
  validmind/tests/model_validation/sklearn/ModelsPerformanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionModelsPerformanceComparison.py
  validmind/tests/model_validation/statsmodels/DurbinWatsonTest.py
  validmind/tests/model_validation/statsmodels/JarqueBera.py
  validmind/tests/model_validation/statsmodels/KolmogorovSmirnov.py
  validmind/tests/model_validation/statsmodels/LJungBox.py
  validmind/tests/model_validation/statsmodels/Lilliefors.py
  validmind/tests/model_validation/statsmodels/PDRatingClassPlot.py
  validmind/tests/model_validation/statsmodels/RegressionModelInsampleComparison.py
  validmind/tests/model_validation/statsmodels/RegressionModelOutsampleComparison.py
  validmind/tests/model_validation/statsmodels/ResidualsVisualInspection.py
  validmind/tests/model_validation/statsmodels/RunsTest.py
  validmind/tests/model_validation/statsmodels/ShapiroWilk.py
Labels: internal

#107 [SC-4820] Fix failing timeseries tests
  notebooks/code_sharing/probability_of_default/economic_model_development.ipynb
  notebooks/code_sharing/probability_of_default/economic_model_validation.ipynb
  notebooks/code_sharing/probability_of_default/helpers/economic_model.py
  notebooks/code_sharing/probability_of_default/helpers/model_development.py
  notebooks/code_sharing/probability_of_default/helpers/scorecard_model.py
  notebooks/code_sharing/probability_of_default/lifetime_pd_model_poc.ipynb
  notebooks/code_sharing/probability_of_default/probability_of_default_demo.ipynb
  pyproject.toml
  tests/test_run_all_tests.py
  validmind/__version__.py
  validmind/test_suites/statsmodels_timeseries.py
  validmind/tests/data_validation/ACFandPACFPlot.py
  validmind/tests/data_validation/ADF.py
  validmind/tests/data_validation/BivariateScatterPlots.py
  validmind/tests/data_validation/DFGLSArch.py
  validmind/tests/data_validation/DefaultRatesbyRiskBandPlot.py
  validmind/tests/data_validation/KPSS.py
  validmind/tests/data_validation/PhillipsPerronArch.py
  validmind/tests/data_validation/PiTCreditScoresHistogram.py
  validmind/tests/data_validation/PiTPDHistogram.py
  validmind/tests/data_validation/TabularDateTimeHistograms.py
  validmind/tests/data_validation/ZivotAndrewsArch.py
  validmind/tests/model_validation/sklearn/RegressionModelsPerformanceComparison.py
  validmind/tests/model_validation/statsmodels/ADFTest.py
  validmind/tests/model_validation/statsmodels/FeatureImportanceAndSignificance.py
  validmind/tests/model_validation/statsmodels/PDRatingClassPlot.py
  validmind/tests/model_validation/statsmodels/RegressionCoeffsPlot.py
  validmind/tests/model_validation/statsmodels/RegressionFeatureSignificance.py
  validmind/tests/model_validation/statsmodels/RegressionModelsCoeffs.py
  validmind/tests/model_validation/statsmodels/RegressionModelsPerformance.py
  validmind/tests/model_validation/statsmodels/ResidualsVisualInspection.py
Labels: internal, chore

#110 [Quickstart] Fixed "Get your code snippet" header
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
Labels: internal

#112 [Low Priority] Add literal type for Test IDs
  .pre-commit-config.yaml
  Makefile
  scripts/generate_test_id_type.py
  validmind/tests/__init__.py
  validmind/tests/__types__.py
Labels: enhancement, internal

#113 Cachafla/additional metric test edits
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#114 FIxed the broken/incorrect anchors in the ToC for "Introduction for Model Developers"
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#109 [SC 4318] Notebook that explains how to use Dataset and Model
  notebooks/how_to/dataset_image.png
  notebooks/how_to/model_image.png
  notebooks/how_to/use_dataset_model_objects.ipynb
  validmind/utils.py
Labels: internal

#111 [SC-4848] Improve timeseries forecasting demo
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/tutorial_time_series_forecasting.ipynb
  notebooks/code_sharing/time_series/loan_rates_forecast_poc.ipynb
  notebooks/code_sharing/time_series/time_series_data_quality_test_plan.ipynb
  notebooks/code_sharing/time_series/time_series_data_validation_full_suite.ipynb
  notebooks/code_sharing/time_series/time_series_demo.ipynb
  notebooks/code_sharing/time_series/time_series_forecast_gls_algo.ipynb
  notebooks/code_sharing/time_series/time_series_forecast_sklearn_linear_regression_algo.ipynb
  notebooks/code_sharing/time_series/time_series_forecast_wls_algo.ipynb
  notebooks/code_sharing/time_series/time_series_model_validation_full_suite.ipynb
  notebooks/code_sharing/time_series/time_series_model_validation_poc.ipynb
  notebooks/code_sharing/time_series/time_series_models_comparison_test_plan.ipynb
  pyproject.toml
  tests/test_validmind_tests_module.py
  validmind/__version__.py
  validmind/datasets/regression/datasets/leanding_club_loan_rates.csv
  validmind/datasets/regression/fred_timeseries.py
  validmind/tests/data_validation/SeasonalDecompose.py
  validmind/tests/data_validation/TimeSeriesDescription.py
  validmind/tests/data_validation/TimeSeriesDescriptiveStatistics.py
  validmind/tests/data_validation/TimeSeriesHistogram.py
  validmind/tests/data_validation/TimeSeriesOutliers.py
  validmind/tests/model_validation/ModelMetadataComparison.py
  validmind/tests/model_validation/ModelPredictionResiduals.py
  validmind/tests/model_validation/TimeSeriesPredictionWithCI.py
  validmind/tests/model_validation/TimeSeriesPredictionsPlot.py
  validmind/tests/model_validation/TimeSeriesR2SquareBySegments.py
  validmind/tests/model_validation/sklearn/FeatureImportanceComparison.py
  validmind/tests/model_validation/sklearn/PermutationFeatureImportance.py
  validmind/tests/model_validation/sklearn/RegressionErrorsComparison.py
  validmind/tests/model_validation/sklearn/RegressionR2SquareComparison.py
Labels: enhancement

#118 [SC-4949] Replace time series notebook in integration tests
  scripts/run_e2e_notebooks.py
Labels: internal, chore

#117 Chore: Dependency Updates
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  .github/workflows/pypi.yaml
  .github/workflows/python.yaml
  README.md
  README.pypi.md
  gradio_apps/README.md
  gradio_apps/prompt_demo.py
  poetry.lock
  pyproject.toml
  scripts/run_e2e_notebooks.py
  validmind/__version__.py
  validmind/datasets/regression/fred_timeseries.py
  validmind/tests/__types__.py
  validmind/tests/data_validation/TimeSeriesDescriptiveStatistics.py
  validmind/tests/model_validation/ModelMetadataComparison.py
  validmind/tests/model_validation/TimeSeriesPredictionWithCI.py
  validmind/tests/model_validation/TimeSeriesPredictionsPlot.py
  validmind/tests/model_validation/TimeSeriesR2SquareBySegments.py
  validmind/tests/model_validation/sklearn/FeatureImportanceComparison.py
  validmind/tests/model_validation/sklearn/RegressionErrorsComparison.py
  validmind/tests/model_validation/sklearn/RegressionR2SquareComparison.py
Labels: internal, chore

#119 John6797/dependency updates
  .github/pull_request_template.md
  .github/workflows/docs.yaml
  .github/workflows/integration.yaml
  .github/workflows/pypi.yaml
  .github/workflows/python.yaml
  .github/workflows/release_notes_check.yaml
  .github/workflows/release_prod.yaml
  .pre-commit-config.yaml
  Makefile
  scripts/credentials_check.py
Labels: bug, internal, chore

#120 John6797/dependency updates
  .github/workflows/integration.yaml
Labels: bug, internal

#121 Updated the required Python versions for the Developer Intro .ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
Labels: internal

#125 Comparison tests notebook
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
  validmind/vm_models/test/result_wrapper.py
Labels: enhancement

#124 `extract_descriptions.py` should support test functions as well
  pyproject.toml
  scripts/extract_descriptions.py
Labels: internal
