Repository validmind/validmind-library, pull requests merged in 2025-03, with the labels that each got.

#326 Restructured old "Introduction for model developers" notebook
  notebooks/templates/about-validmind.ipynb
  notebooks/templates/install-initialize-validmind.ipynb
  notebooks/templates/next-steps.ipynb
  notebooks/tutorials/model_development/101-set_up_validmind.ipynb
  notebooks/tutorials/model_development/102-start_development_process.ipynb
  notebooks/tutorials/model_development/103-integrate_custom_tests.ipynb
  notebooks/tutorials/model_development/104-finalize_testing_documentation.ipynb
  notebooks/tutorials/model_development/add-content-block.gif
  notebooks/tutorials/model_development/high-pearson-correlation-block.png
  notebooks/tutorials/model_development/my_tests_directory.png
  notebooks/tutorials/model_development/selecting-confusion-matrix-test.png
  notebooks/tutorials/model_development/selecting-high-pearson-correlation-test.png
Labels: documentation, highlight

#327 Always overwrite metadata
  poetry.lock
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/result/utils.py
Labels: internal

#329 Bring `release-2.7` changes into `main`
  .github/workflows/pypi.yaml
  poetry.lock
  pyproject.toml
  validmind/vm_models/result/utils.py
Labels: internal

#333 [SC-8983] Remove ydata-profiling library dependency
  poetry.lock
  pyproject.toml
  tests/unit_tests/data_validation/test_DatasetDescription.py
  validmind/tests/data_validation/DatasetDescription.py
  validmind/tests/data_validation/Skewness.py
  validmind/utils.py
Labels: internal

#335 [SC-9912] Fix index issue when using input_grid
  validmind/tests/model_validation/sklearn/WeakspotsDiagnosis.py
Labels: bug, internal

#336 [SC 8983] Remove inferring datatype warnings
  validmind/utils.py
Labels: internal

#331 Cleanup of links out to the ValidMind Library docs
  README.md
  README.pypi.md
  notebooks/README.md
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_executive.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_full_suite.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_ml.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/application_scorecard_ongoing_monitoring.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/code_sharing/embeddings/quickstart_embeddings_demo.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/output_templates/customizing_tests_with_output_templates.ipynb
  notebooks/code_sharing/r/r_custom_tests.Rmd
  notebooks/code_sharing/regression/regression_unit_metrics.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/log_metrics_over_time.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/templates/README.md
  notebooks/templates/about-validmind.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  notebooks/tutorials/model_development/101-set_up_validmind.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#334 [SC 9106] Include number of records in the overfit diagnosis test
  validmind/tests/model_validation/sklearn/OverfitDiagnosis.py
Labels: internal

#337 [SC 8805] support config option for logging test results
  tests/test_api_client.py
  validmind/api_client.py
  validmind/errors.py
  validmind/vm_models/result/result.py
Labels: documentation, enhancement

#338 New validation notebook: Validate an application scorecard model
  .gitignore
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models_quantlib.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_executive.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_full_suite.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_ml.ipynb
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/model_validation/validate_application_scorecard.ipynb
  notebooks/code_samples/model_validation/xgb_model_champion.pkl
  notebooks/code_samples/nlp_and_llm/prompt_validation_demo.ipynb
  notebooks/code_samples/nlp_and_llm/rag_documentation_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/application_scorecard_ongoing_monitoring.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_full_suite.ipynb
  notebooks/code_samples/time_series/quickstart_time_series_high_code.ipynb
  notebooks/code_sharing/operational_deposit/operational_deposit_poc.ipynb
  notebooks/code_sharing/output_templates/customizing_tests_with_output_templates.ipynb
  notebooks/how_to/add_context_to_llm_descriptions.ipynb
  notebooks/how_to/configure_dataset_features.ipynb
  notebooks/how_to/document_multiple_results_for_the_same_test.ipynb
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/load_datasets_predictions.ipynb
  notebooks/how_to/log_metrics_over_time.ipynb
  notebooks/how_to/run_documentation_sections.ipynb
  notebooks/how_to/run_documentation_tests_with_config.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/how_to/run_tests_that_require_multiple_datasets.ipynb
  notebooks/how_to/run_unit_metrics.ipynb
  notebooks/how_to/use_dataset_model_objects.ipynb
  notebooks/templates/about-validmind.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  notebooks/tutorials/model_development/101-set_up_validmind.ipynb
  notebooks/tutorials/model_development/102-start_development_process.ipynb
  notebooks/tutorials/model_development/103-integrate_custom_tests.ipynb
  notebooks/tutorials/model_development/104-finalize_testing_documentation.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: documentation, enhancement
