Repository validmind/validmind-library, pull requests merged in 2025-04, with the labels that each got.

#341 [SC-7456] intro_for_model_developers.ipynb throws SHAPGlobalImportance.py error
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/sklearn/SHAPGlobalImportance.py
Labels: bug, internal

#342 Remove GH_TOKEN requirement
  .github/workflows/docs.yaml
  .github/workflows/quarto-docs.yaml
  docs/_sidebar.yml
  docs/validmind.qmd
  docs/validmind/tests.qmd
  docs/validmind/version.qmd
Labels: internal

#343 Add "data_quality" tag ClassImbalance and DescriptiveStatistics tests
  notebooks/how_to/explore_tests.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/data_validation/ClassImbalance.py
  validmind/tests/data_validation/DescriptiveStatistics.py
  validmind/tests/load.py
Labels: internal

#344 Remove some pdoc remnants
  .github/workflows/quarto-docs.yaml
  docs/templates/custom.css
  docs/templates/module.html.jinja2
Labels: internal

#346 [SC-9395] Add RAG benchmarking demo notebook
  notebooks/code_samples/nlp_and_llm/rag_benchmark_demo.ipynb
  poetry.lock
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/ragas/AnswerCorrectness.py
  validmind/tests/model_validation/ragas/ContextEntityRecall.py
  validmind/tests/model_validation/ragas/ContextPrecision.py
  validmind/tests/model_validation/ragas/ContextPrecisionWithoutReference.py
  validmind/tests/model_validation/ragas/ContextRecall.py
  validmind/tests/model_validation/ragas/Faithfulness.py
  validmind/tests/model_validation/ragas/ResponseRelevancy.py
  validmind/tests/model_validation/ragas/SemanticSimilarity.py
Labels: documentation, enhancement

#350 Updates for Python Library API & model development placeholder
  docs/_sidebar.yml
  docs/templates/module.qmd.jinja2
  docs/templates/sidebar.qmd.jinja2
  docs/validmind.qmd
  notebooks/code_samples/model_validation/validate_application_scorecard.ipynb
  notebooks/tutorials/intro_for_model_developers.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#351 John6797/sc 9452/add check for too many plots for test description
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
Labels: bug, internal

#352 Hotfix: customize title for test
  validmind/tests/run.py
Labels: bug, internal

#355 [SC 9539] Keep order of the sections while previewing the template
  validmind/template.py
Labels: bug, internal

#356 [SC-9919] Fix pandas DataFrame dtype preservation in VMDataset initialization
  pyproject.toml
  tests/test_dataset.py
  validmind/__version__.py
  validmind/client.py
  validmind/vm_models/dataset/dataset.py
Labels: bug, internal

#360 Improve performance of feature_columns_numeric and feature_columns_categorical
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/dataset/dataset.py
Labels: internal
