Repository validmind/validmind-library, pull requests merged in 2025-05, with the labels that each got.

#363 chore: sync pr template from backend
  .github/pull_request_template.md
Labels: internal

#358 [SC 9566] Interfaces to support code explainer
  validmind/__init__.py
  validmind/experimental/__init__.py
  validmind/experimental/agents.py
  validmind/vm_models/result/__init__.py
  validmind/vm_models/result/result.py
Labels: documentation, enhancement, highlight

#354 [SC-9555] Added section to inject custom context via docstring
  .github/workflows/release_notes_check.yaml
  notebooks/how_to/add_context_to_llm_descriptions.ipynb
  notebooks/tutorials/model_development/2-start_development_process.ipynb
  notebooks/tutorials/model_development/3-integrate_custom_tests.ipynb
  notebooks/tutorials/model_development/add-content-block.gif
  notebooks/tutorials/model_development/selecting-confusion-matrix-test.png
  notebooks/tutorials/model_development/selecting-high-pearson-correlation-test.png
  notebooks/tutorials/model_validation/3-developing_challenger_model.ipynb
Labels: documentation, enhancement

#364 Repo Sync repo-sync/9683 (2025-05-05)
  .github/pull_request_template.md
Labels: internal

#365 [SC-10190] Git ignore .direnv/ and .envrc
  .gitignore
Labels: internal

#367 Notebooks: Fixing wrong images & typos in validation series
  notebooks/tutorials/model_validation/2-start_validation_process.ipynb
  notebooks/tutorials/model_validation/3-developing_challenger_model.ipynb
  notebooks/tutorials/model_validation/link-finding.png
  notebooks/tutorials/model_validation/link-validator-evidence.png
  notebooks/tutorials/model_validation/link-validator-evidence_OLD.png
  pyproject.toml
  validmind/__version__.py
Labels: internal

#370 notebooks: Edited validator permissions + added links to training
  notebooks/tutorials/model_development/1-set_up_validmind.ipynb
  notebooks/tutorials/model_development/2-start_development_process.ipynb
  notebooks/tutorials/model_development/3-integrate_custom_tests.ipynb
  notebooks/tutorials/model_development/4-finalize_testing_documentation.ipynb
  notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.ipynb
  notebooks/tutorials/model_validation/2-start_validation_process.ipynb
  notebooks/tutorials/model_validation/3-developing_challenger_model.ipynb
  notebooks/tutorials/model_validation/4-finalize_validation_reporting.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#368 [SC 10242] Update pytorch version to 2.7.0
  poetry.lock
  pyproject.toml
Labels: internal

#371 Hotfix: Update content_id logic in metadata update function
  tests/test_results.py
  validmind/vm_models/result/result.py
Labels: bug, internal

#372 notebooks: Quickstart for model documentation edit
  notebooks/README.md
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
  notebooks/quickstart/quickstart_model_documentation.ipynb
  notebooks/templates/next-steps.ipynb
  notebooks/tutorials/model_development/2-start_development_process.ipynb
  notebooks/tutorials/model_validation/2-start_validation_process.ipynb
  scripts/run_e2e_notebooks.py
Labels: enhancement

#359 delete test_get_metadata test
  tests/test_api_client.py
Labels: internal

#366 [SC 10123 ] Support qualitative text generation
  validmind/experimental/agents.py
Labels: enhancement
