Repository validmind/validmind-library, pull requests merged in 2025-01, with the labels that each got.

#256 [SC-7588] Explore dynamic llm context injection in test descriptions
  notebooks/code_sharing/llm/llm_descriptions_context.ipynb
  validmind/ai/test_descriptions.py
  validmind/ai/test_result_description/user.jinja
Labels: internal

#281 John6797/sc 7795/add better handling for description futures
  validmind/tests/run.py
Labels: enhancement, internal

#282 End-to-end notebook template generation script
  Makefile
  notebooks/README.md
  notebooks/templates/README.md
  notebooks/templates/about-validmind.ipynb
  notebooks/templates/e2e-notebook.ipynb
  notebooks/templates/e2e_template.py
  notebooks/templates/install-initialize-validmind.ipynb
  notebooks/templates/next-steps.ipynb
  notebooks/templates/upgrade-validmind.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#283 John6797/sc 7776/add more coverage to integration unit tests
  scripts/run_e2e_notebooks.py
  tests/test_validmind_tests_module.py
  validmind/tests/decorator.py
  validmind/tests/run.py
Labels: bug, internal, chore

#280 [SC-7864] Create credit risk scorecard notebook using XGBoost
  notebooks/code_samples/credit_risk/application_scorecard_full_suite.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_ml.ipynb
  pyproject.toml
  tests/test_integration_tests.py
  tests/unit_tests/data_validation/test_TooManyZeroValues.py
  tests/unit_tests/data_validation/test_UniqueRows.py
  validmind/__version__.py
  validmind/datasets/credit_risk/lending_club.py
  validmind/tests/data_validation/MutualInformation.py
  validmind/tests/data_validation/ScoreBandDefaultRates.py
  validmind/tests/data_validation/TooManyZeroValues.py
  validmind/tests/data_validation/UniqueRows.py
  validmind/tests/model_validation/sklearn/CalibrationCurve.py
  validmind/tests/model_validation/sklearn/ClassifierThresholdOptimization.py
  validmind/tests/model_validation/sklearn/ConfusionMatrix.py
  validmind/tests/model_validation/sklearn/HyperParametersTuning.py
  validmind/tests/model_validation/sklearn/ModelParameters.py
  validmind/tests/model_validation/sklearn/ScoreProbabilityAlignment.py
  validmind/tests/model_validation/statsmodels/CumulativePredictionProbabilities.py
  validmind/tests/model_validation/statsmodels/PredictionProbabilitiesHistogram.py
  validmind/utils.py
Labels: internal

#286 add as_json tag
  validmind/tests/load.py
Labels: internal

#290 [SC-8008] Ongoing monitoring notebook for application scorecard model
  notebooks/code_samples/credit_risk/application_scorecard_executive.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_full_suite.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_ml.ipynb
  notebooks/code_samples/credit_risk/custom_tests/ScoreBandDiscriminationMetrics.py
  notebooks/code_samples/ongoing_monitoring/application_scorecard_ongoing_monitoring.ipynb
  pyproject.toml
  tests/test_integration_tests.py
  validmind/__version__.py
  validmind/datasets/credit_risk/lending_club.py
  validmind/tests/data_validation/HighPearsonCorrelation.py
  validmind/tests/ongoing_monitoring/CalibrationCurveDrift.py
  validmind/tests/ongoing_monitoring/ClassDiscriminationDrift.py
  validmind/tests/ongoing_monitoring/ClassImbalanceDrift.py
  validmind/tests/ongoing_monitoring/ClassificationAccuracyDrift.py
  validmind/tests/ongoing_monitoring/ConfusionMatrixDrift.py
  validmind/tests/ongoing_monitoring/CumulativePredictionProbabilitiesDrift.py
  validmind/tests/ongoing_monitoring/FeatureDrift.py
  validmind/tests/ongoing_monitoring/PredictionAcrossEachFeature.py
  validmind/tests/ongoing_monitoring/PredictionCorrelation.py
  validmind/tests/ongoing_monitoring/PredictionProbabilitiesHistogramDrift.py
  validmind/tests/ongoing_monitoring/PredictionQuantilesAcrossFeatures.py
  validmind/tests/ongoing_monitoring/ROCCurveDrift.py
  validmind/tests/ongoing_monitoring/ScoreBandsDrift.py
  validmind/tests/ongoing_monitoring/ScorecardHistogramDrift.py
  validmind/tests/ongoing_monitoring/TargetPredictionDistributionPlot.py
  validmind/vm_models/dataset/dataset.py
Labels: internal

#291 Fix: Updating scikit-learn in pyproject.toml
  poetry.lock
  pyproject.toml
Labels: internal

#294 John6797/sc 8121/switch from mathml to mathjax for latex formulas
  poetry.lock
  pyproject.toml
  validmind/html_templates/content_blocks.py
  validmind/utils.py
Labels: internal, refactor

#296 John6797/sc 7670/move test result description prompts to backend
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/ai/test_result_description/config.yaml
  validmind/ai/test_result_description/context.py
  validmind/ai/test_result_description/image_processing.py
  validmind/ai/test_result_description/system.jinja
  validmind/ai/test_result_description/user.jinja
  validmind/api_client.py
  validmind/tests/run.py
Labels: enhancement, internal

#298 Remove `rpy2` Dependency
  README.md
  README.pypi.md
  poetry.lock
  pyproject.toml
  validmind/__init__.py
  validmind/errors.py
  validmind/models/r_model.py
  validmind/tests/data_validation/FeatureTargetCorrelationPlot.py
  validmind/tests/model_validation/ContextualRecall.py
  validmind/tests/model_validation/MeteorScore.py
  validmind/tests/model_validation/ToxicityScore.py
  validmind/tests/model_validation/sklearn/MinimumROCAUCScore.py
  validmind/tests/model_validation/statsmodels/RegressionModelSummary.py
Labels: internal, chore

#299 +definition `print_env()` for developer reference
  pyproject.toml
  validmind/__version__.py
  validmind/tests/run.py
Labels: internal

#300 John6797/sc 8257/regularly check if the user is using an older
  pyproject.toml
  validmind/__init__.py
  validmind/__version__.py
  validmind/utils.py
Labels: enhancement, internal

#302 [SC-8300] Fix: Store embeddings in dictionary instead of DataFrame
  pyproject.toml
  validmind/__version__.py
  validmind/tests/model_validation/embeddings/StabilityAnalysisRandomNoise.py
  validmind/tests/model_validation/embeddings/StabilityAnalysisSynonyms.py
  validmind/tests/model_validation/embeddings/StabilityAnalysisTranslation.py
  validmind/tests/model_validation/embeddings/utils.py
Labels: bug, internal

#303 John6797/sc 8157/add genai description toggle as argument
  poetry.lock
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/api_client.py
  validmind/tests/model_validation/ragas/utils.py
  validmind/tests/prompt_validation/ai_powered_test.py
Labels: enhancement, internal

#301 Cleanup of "Log metrics over time" notebook in preparation for docs
  notebooks/how_to/log_metrics_over_time.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#305 Forgot an end div omg
  notebooks/how_to/log_metrics_over_time.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#304 Fix: Adding Missing `RawData` Support to Comparison Tests
  pyproject.toml
  scripts/run_e2e_notebooks.py
  validmind/__version__.py
  validmind/tests/comparison.py
  validmind/tests/run.py
Labels: enhancement, internal

#307 Edited adding context to LLM-generated descriptions notebook
  notebooks/code_sharing/llm/add_context_to_llm_descriptions.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal
