Repository validmind/validmind-library, pull requests merged in 2025-07, with the labels that each got.

#392 [SC-11248] Hotfix: Test results not being logged to API when no tables present
  pyproject.toml
  validmind/__version__.py
  validmind/ai/utils.py
  validmind/vm_models/result/result.py
Labels: bug, internal

#385 Edit `how_to` notebooks: Explore test suites
  notebooks/how_to/explore_test_suites.ipynb
  notebooks/how_to/explore_test_suites_output.png
  notebooks/how_to/test_suite_output1.png
  notebooks/how_to/test_suite_output2.png
Labels: internal

#394 Extend the predict_fn in the init_model to support multiple output columns
  notebooks/agents/langchain_agent_simple_demo.ipynb
  notebooks/agents/langchain_utils.py
  notebooks/agents/langgraph_agent_demo.ipynb
  notebooks/agents/langgraph_agent_simple_demo.ipynb
  notebooks/agents/utils.py
  tests/test_dataset.py
  validmind/models/function.py
  validmind/vm_models/dataset/dataset.py
Labels: documentation

#396 notebooks: Edits for document types UI update
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_executive.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_full_suite.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_bias.ipynb
  notebooks/code_samples/credit_risk/application_scorecard_with_ml.ipynb
  notebooks/code_samples/model_validation/validate_application_scorecard.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/foundation_models_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_integration_demo.ipynb
  notebooks/code_samples/nlp_and_llm/hugging_face_summarization_demo.ipynb
  notebooks/code_samples/nlp_and_llm/llm_summarization_demo.ipynb
  notebooks/code_samples/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb
  notebooks/code_samples/regression/quickstart_regression_full_suite.ipynb
  notebooks/code_sharing/clustering/quickstart_cluster_demo.ipynb
  notebooks/how_to/run_tests/1_run_dataset_based_tests.ipynb
  notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
  notebooks/quickstart/quickstart_model_documentation.ipynb
  notebooks/quickstart/quickstart_model_validation.ipynb
  notebooks/tutorials/model_development/1-set_up_validmind.ipynb
  notebooks/tutorials/model_development/2-start_development_process.ipynb
  notebooks/tutorials/model_development/3-integrate_custom_tests.ipynb
  notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.ipynb
  notebooks/tutorials/model_validation/2-start_validation_process.ipynb
  notebooks/tutorials/model_validation/3-developing_challenger_model.ipynb
Labels: internal
