Repository validmind/validmind-library, pull requests merged in 2025-08, with the labels that each got.

#395 Add generalize plots and statistical tests
  notebooks/code_sharing/plots_and_stats_demo.ipynb
  validmind/tests/__init__.py
  validmind/tests/plots/BoxPlot.py
  validmind/tests/plots/CorrelationHeatmap.py
  validmind/tests/plots/HistogramPlot.py
  validmind/tests/plots/ViolinPlot.py
  validmind/tests/plots/__init__.py
  validmind/tests/stats/CorrelationAnalysis.py
  validmind/tests/stats/DescriptiveStats.py
  validmind/tests/stats/NormalityTests.py
  validmind/tests/stats/OutlierDetection.py
  validmind/tests/stats/__init__.py
Labels: enhancement

#408 [SC-11665] Remove scorecard with GLM notebook
  notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb
  pyproject.toml
  validmind/__version__.py
  validmind/tests/__types__.py
Labels: deprecation, chore

#411 [SC-11676] Improve API timeout support to prevent timeouts with large datasets
  pyproject.toml
  validmind/__version__.py
  validmind/api_client.py
  validmind/logging.py
  validmind/vm_models/result/result.py
Labels: bug

#410 SC-2886: PII Detection for Uploaded Test Results
  .github/workflows/integration.yaml
  README.md
  notebooks/how_to/configure_pii_detection.ipynb
  poetry.lock
  pyproject.toml
  scripts/run_e2e_notebooks.py
  tests/test_results.py
  validmind/ai/test_descriptions.py
  validmind/ai/utils.py
  validmind/api_client.py
  validmind/tests/data_validation/ScoreBandDefaultRates.py
  validmind/tests/model_validation/embeddings/PCAComponentsPairwisePlots.py
  validmind/tests/model_validation/embeddings/TSNEComponentsPairwisePlots.py
  validmind/tests/model_validation/sklearn/RobustnessDiagnosis.py
  validmind/tests/model_validation/statsmodels/CumulativePredictionProbabilities.py
  validmind/tests/model_validation/statsmodels/PredictionProbabilitiesHistogram.py
  validmind/tests/model_validation/statsmodels/ScorecardHistogram.py
  validmind/tests/ongoing_monitoring/CalibrationCurveDrift.py
  validmind/tests/ongoing_monitoring/PredictionProbabilitiesHistogramDrift.py
  validmind/tests/ongoing_monitoring/ScoreBandsDrift.py
  validmind/tests/ongoing_monitoring/ScorecardHistogramDrift.py
  validmind/tests/plots/BoxPlot.py
  validmind/tests/plots/HistogramPlot.py
  validmind/tests/stats/DescriptiveStats.py
  validmind/vm_models/result/pii_filter.py
  validmind/vm_models/result/result.py
  validmind/vm_models/result/utils.py
Labels: enhancement, internal

#416 notebook: Enable PII detection in tests
  notebooks/how_to/configure_pii_detection.ipynb
  notebooks/how_to/enable_pii_detection.ipynb
Labels: documentation, highlight

#418 Hotfix: Remove LLM is_configured() Check from Test Description Generation
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
Labels: bug, internal

#419 Bring Hotfix To `main`
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
Labels: internal
