Repository validmind/validmind-library, pull requests merged in 2025-02, with the labels that each got.

#308 Moved add context notebook to `how_to`
  notebooks/how_to/add_context_to_llm_descriptions.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: internal

#309 Notebook to show Raw Data Feature
  notebooks/how_to/understand_utilize_rawdata.ipynb
  validmind/utils.py
Labels: documentation, internal, chore

#311 fix: handle context length too large
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
  validmind/tests/run.py
Labels: bug, internal

#315 [SC 8504] Missing definition of the parameters in the capital markets model notebook
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  pyproject.toml
  validmind/__version__.py
Labels: bug, internal

#318 +`breaking-changes` tag to PR template
  .github/pull_request_template.md
Labels: internal

#316 [SC-8240] Add warning message for unregistered tests in template
  pyproject.toml
  validmind/__version__.py
  validmind/vm_models/result/result.py
Labels: internal, chore

#319 Prod 2.7.9 to main
  notebooks/code_samples/capital_markets/quickstart_option_pricing_models.ipynb
  poetry.lock
  pyproject.toml
  tests/test_unit_tests.py
  tests/unit_tests/model_validation/test_TimeSeriesPredictionWithCI.py
  tests/unit_tests/model_validation/test_TimeSeriesPredictionsPlot.py
  validmind/ai/test_descriptions.py
  validmind/utils.py
Labels: internal

#322 John6797/hotfix for test description generation errors
  pyproject.toml
  validmind/__version__.py
  validmind/ai/test_descriptions.py
Labels: bug, internal

#324 ci: Add release-2.7 branch to PyPI workflow
  .github/workflows/pypi.yaml
Labels: internal

#325 Hotfix pandas encoder 2.7
  notebooks/code_samples/custom_tests/implement_custom_tests.ipynb
  notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb
  notebooks/images/btc-price-custom-metric.png
  notebooks/images/external-data-custom-test.png
  poetry.lock
  pyproject.toml
  tests/test_unit_tests.py
  tests/unit_tests/model_validation/test_TimeSeriesPredictionWithCI.py
  tests/unit_tests/model_validation/test_TimeSeriesPredictionsPlot.py
  validmind/__version__.py
  validmind/errors.py
  validmind/utils.py
Labels: bug, internal
